### ISSUE TITLE
psf.trn  transfer to psf.csv ---data transfer 

### ISSUE THREAD

**Issue by 1232233s** [KenKundert/psf_utils#15]
command :simvisdbutil psf.trn -csv -timeunits s -output psf.csv
my psf.trn is almost 392M.(data space)
but the psf.csv reach out to  19G. it's pretty large.

**Comment by KenKundert** [comment]
Unfortunately, *psf_utils* is only suitable for relatively small PSF ASCII files.  I don't know why, but Cadence makes it difficult to build your own analysis tools for Spectre results.  Specifically, as far as I am aware, they offer no Python libraries for reading their data files and they do not document their formats so one could write one's own reader.  I created *psf_utils* for my needs and I no longer simulate large circuits so the low density of the PSF ASCII files was not a problem for me, but the fact that I could easily view the structure of the files and use that information to construct a parser made the work tractable.

At this point I am done. *psf_utils* meets my needs as it is, and I suspect it would be a significant amount of unpleasant work to try to reverse engineer the PSF binary format, so I have no plans to do so.  Also I have no plans to write an SST file reader.  Again, I currently have no need for one.

**Comment by 1232233s** [comment]
your lib is very cool . yeh , i know there is a API to access SST file, it was very convenient and quickly . maybe it is a good solution for this problem.
