### ISSUE TITLE
inf keyword in dcOpInfo files is not parsed correctly

### ISSUE THREAD

**Issue by kove87** [KenKundert/psf_utils#17]
When reading in a psfascii file containing dc operating point information. I get the following error:
```
psf_utils.parse.ParseError: dcOpInfo.info.mod.pfsascii(72377): illegal character 'i'.
    inf
```

work around: a find and replace of inf to nan in the data file.

**Comment by KenKundert** [comment]
Can you get me an example file so I can test any fix?

**Comment by KenKundert** [comment]
I have updated the github repository with a proposed fix.  Would you please download and try it.

**Comment by kove87** [comment]
The updated code works! Thanks for the update.

**Comment by KenKundert** [comment]
May take some time to get this into pypi.  Will that be an issue for you?

**Comment by kove87** [comment]
No issue at all.

**Comment by KenKundert** [comment]
This fix is now available in PyPi.
