### ISSUE TITLE
DC sim results give rise to syntax error

### ISSUE THREAD

**Issue by JoopBanaan** [KenKundert/psf_utils#3]
Reading a DC simulation result, gives a syntax error 'Value' in the enclosed file at line 84

I use Spectre: Version 19.1.0.373.isr7 64bit -- 21 May 2020
psf-utils=1.1.0
ply=3.11
python=3.9

[dc.txt](https://github.com/KenKundert/psf_utils/files/5911125/dc.txt)
and a sim result without saving currents: [dc no currents.txt](https://github.com/KenKundert/psf_utils/files/5911429/dc.no.currents.txt)

**Comment by KenKundert** [comment]
I had not considered scalar results (dc op point) and currently the program is not set up for it. May take a while.

**Comment by KenKundert** [comment]
Okay, I have updated the library on github to support DC op-point datasets.  Not terrible well tested, but please give it a try.

**Comment by KenKundert** [comment]
I have updated pipy. Version 1.2. Thanks for the report.
