### ISSUE TITLE
Psf Util Issue

### ISSUE THREAD

**Issue by pharushi** [KenKundert/psf_utils#4]
So I came across your library PSF_Utils. I converted the PSF raw format to ascii using psf utility.When I was trying to read the ascii file I am getting a error.
"/env/lib64/python3.6/site-packages/psf_utils/parse.py:136: Rule 't_ID' returned an unknown token type 'ID'"
I am unable to find what is causing the error. I think it has to do with the RESERVED tokens which are declared in "parse.py" file.
I would be very helpful if you would help me in this.
I am attaching my ascii file.

[tran.txt](https://github.com/KenKundert/psf_utils/files/5914867/tran.txt)

**Comment by KenKundert** [comment]
I have updated psf_utils on github. I think the latest version resolves your issue. Please give it a try and let me know.

**Comment by pharushi** [comment]
Yes, it works perfectly. Thank you!

**Comment by KenKundert** [comment]
I have updated pipy. Version 1.2.  Thanks for the report.
