### ISSUE TITLE
Unknown keyword 'INT'

### ISSUE THREAD

**Issue by MarioAuer** [KenKundert/psf_utils#5]
I get the following error:

list-psf error:
    dcOpInfo.info.psfascii(409): unknown keyword 'INT'.
        "region" INT BYTE PROP(

The psf file (see upload) contains
```
"region" INT BYTE PROP(
"description" "Estimated operating region. Spectre outputs number (0-4) in a rawfile"
)
```

[dcOpInfo.info.psfascii.zip](https://github.com/KenKundert/psf_utils/files/6176221/dcOpInfo.info.psfascii.zip)

**Comment by KenKundert** [comment]
I have fixed it on github. Please try it and let me know if you have any trouble.

**Comment by MarioAuer** [comment]
Works perfectly :-)
Thank you very much for improving and of course creating this library!

**Comment by KenKundert** [comment]
Thank Mario.  I have uploaded the latest version (1.3) to pypi so you can now get it with pip.

**Comment by MarioAuer** [comment]
Thank you!
