### ISSUE TITLE
unknown keyword 'LONG'

### ISSUE THREAD

**Issue by asereq** [KenKundert/psf_utils#8]
I get the following error:

```
list-psf error:
    dcOpInfo.psf(134): unknown keyword 'LONG'.
        "diode_region" INT LONG PROP(
                           ^
```

The psf file ([dcOpInfo.txt](https://github.com/KenKundert/psf_utils/files/7513530/dcOpInfo.txt)) contains

```
"diode_region" INT LONG PROP(
"description" "DIODE region"
)
```

**Comment by KenKundert** [comment]
Sorry about that. PSF seems to have an endless set of variations on the same theme.  I have updated the github version if you would like to try it out.  I will be making a few more improvements before I push the new version to pypi.  Please let me know if the github version fixes your problem.

**Comment by asereq** [comment]
No problem, I understand the difficult of the undocumented format. Thanks for your time. And yes, the github version seems to solve the problem, thanks again.

**Comment by KenKundert** [comment]
I have updated pypi to version 1.5, which includes the code to fix your issue.  Thanks for reporting it.
